FROM golang:1.20-alpine

WORKDIR /app

# Copia o código da sirene para dentro do container
COPY actorSiren.go .

# Compila o executável
RUN go build -o actorSiren actorSiren.go

# Define o ponto de entrada. O Docker Compose vai passar o IP e a Porta como argumentos
ENTRYPOINT ["./actorSiren"]