FROM golang:1.22-alpine AS builder
WORKDIR /app
COPY sensorFuel.go .
RUN go build -o fuel sensorFuel.go

FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/fuel .
ENTRYPOINT ["./fuel"]